---
title: "Making static maps"
author: "Matt Williamson"
date: "10/20/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Your assignment

The goals for this assignment are to:

- practice making maps with the various packages
- think about composition and the grammar of graphics
- critique various maps

_By the end of the assignment_ you should have several static maps displaying the datasets we've used in the last few weeks.

# Task 1: Show me your ugly maps!!
Find 2 examples of maps that you think are 'bad'. 
_Question 1_ Why are they bad? What might improve them? 
_Question 2_ Rely on the Healy and Wilke texts to provide some structure to your answers.

# Task 2: Load your libraries and build a dataframe
You can choose whichever datasets you'd like from the past several months as the subject for your mapping. You'll need to use at least one tabular join, one spatial join, and one extraction to create the dataframe. Load the packages, the data, and make sure everything is projected here. Give me a sense for what you are hoping to map.


# Task 3: Build a map with Tmap
Practice making a quick map with tmap. 


# Task 4: Build a choropleth with ggplot
Your map should have a basemap, should rely on more than one aesthetic (color, transparency, etc), and combine multiple layers.

# Task 5: Build 2 cartograms
Follow the examples to build cartograms that display your region of interest based on variables other than area.

_Question 3:_ Reflect on the different maps you've made, what do the different visualizations tell you about the data you plotted?

_Question 4:_ How might you improve the maps you've made?

_Question 5:_ Is a map the best way to evaluate the data you worked with? Why or Why not?


